#!/bin/sh
CUR_MONTH=$(date +%-m)   # %-m = month without leading zero
CUR_YEAR=$(date +%Y)

loop() {
	clear
	cal "$CUR_MONTH" "$CUR_YEAR"
	read -sn1 x
	if [ "$x" == "l" ]; then
		CUR_MONTH=$(( CUR_MONTH + 1 ))
		if [ "$CUR_MONTH" -gt 12 ]; then
			CUR_MONTH=1
			CUR_YEAR=$(( CUR_YEAR + 1 ))
		fi
		loop
	elif [ "$x" == "h" ]; then
		CUR_MONTH=$(( CUR_MONTH - 1 ))
		if [ "$CUR_MONTH" -lt 1 ]; then
			CUR_MONTH=12
			CUR_YEAR=$(( CUR_YEAR - 1 ))
		fi
		loop
	elif [ "$x" != "q" ] && [ "$x" != "" ]; then
		loop
	fi
}
loop
exit
