# preload = /home/antonio/Pictures/WallpaperSlides/fuji_1080.jpg
# wallpaper = ,/home/antonio/Pictures/WallpaperSlides/fuji_1080.jpg
# preload = /home/antonio/Pictures/WallpaperSlides/alexandr_podvalny_landscape_mod_1080.jpg
# wallpaper = ,/home/antonio/Pictures/WallpaperSlides/alexandr_podvalny_landscape_mod_1080.jpg

splash = false

wallpaper {
    monitor = eDP-1
    path = /home/antonio/Pictures/WallpaperSlides/alexandr_podvalny_landscape_mod_1080.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/antonio/Pictures/WallpaperSlides/alexandr_podvalny_landscape_mod_1080.jpg
    fit_mode = cover
}
